# Generated by Django 3.2.18 on 2023-02-18 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userogin',
            new_name='userlogin',
        ),
    ]
