# Generated by Django 3.2.18 on 2023-02-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_userogin_userlogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
